ude_test:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
    
# Joint Trajectory Controller -----------------------
  ude_controller:
    type: effort_controllers/JointTrajectoryController
    joints: 
      - joint1  
      - joint2
      - joint3  
      - joint4  
    gains:
      joint1: {p: 100,  d: 0.01, i: 10.0, i_clamp: 0}
      joint2: {p: 100,  d: 0.01, i: 10.0, i_clamp: 0}
      joint3: {p: 100,  d: 0.01, i: 10.0, i_clamp: 0}
      joint4: {p: 100,  d: 0.01, i: 10.0, i_clamp: 0} 
    allow_partial_joints_goal: true
    constraints:
      goal_time: 1.0 
      stopped_velocity_tolerance: 1.0 # Override default
      joint1: {trajectory: 0.0, goal: 0.0}
      joint2: {trajectory: 0.0, goal: 0.0}
      joint3: {trajectory: 0.0, goal: 0.0}
      joint4: {trajectory: 0.0, goal: 0.0}
    stop_trajectory_duration: 0.5        # Override default
    state_publish_rate:  25            # Override default
    action_monitor_rate: 30            # Override default
    
    #Needed for position_controllers/JointTrajectoryController
  gazebo_ros_control:
    pid_gains:
      joint1: {p: 100.0, i: 0.01, d: 10.0}
      joint2: {p: 100.0, i: 0.01, d: 10.0}
      joint3: {p: 100.0, i: 0.01, d: 10.0}
      joint4: {p: 100.0, i: 0.01, d: 10.0}

  #For DEBUGGING Gazebo_ros_control
  joint1_position_controller:
    type: effort_controllers/JointPositionController #position_controllers/JointPositionController
    joint: joint1
    pid: {p: 1.0, i: 0, d: 0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController #position_controllers/JointPositionController
    joint: joint2
    pid: {p: 1.0, i: 0, d: 0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController #position_controllers/JointPositionController
    joint: joint3
    pid: {p: 1.0, i: 0, d: 0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController #position_controllers/JointPositionController
    joint: joint4
    pid: {p: 1.0, i: 0, d: 0}